version: '3.7'

volumes:
    solidity_compilers: {}
    vyper_compilers: {}
    brownie: {}
    cache: {}

x-common-volumes: &common-volumes
  - solidity_compilers:/root/.solcx
  - vyper_compilers:/root/.vvm
  - brownie:/root/.brownie
  - cache:/app/yearn-exporter/cache

x-common-envs: &common-envs
  - SENTRY_DSN:
  - SENTRY_RELEASE:
  - SENTRY_ENVIRONMENT:
  - BRIDGE_PORT: 1337

x-common-eth-envs: &common-eth-envs
  - WEB3_PROVIDER:
  - EXPLORER:
  - NETWORK: mainnet
  - ETHERSCAN_TOKEN:

x-common-ftm-envs: &common-ftm-envs
  - NETWORK: ftm-main
  - WEB3_PROVIDER: $FTM_WEB3_PROVIDER
  - EXPLORER: $FTM_EXPLORER
  - FTMSCAN_TOKEN:

networks:
  yearn-brownie-bridge:

services:
  brownie-bridge-eth:
    build: .
    image: yearn-exporter
    command: brownie_bridge
    volumes: *common-volumes
    environment:
      <<: *common-envs
      <<: *common-eth-envs
    ports:
      - 127.0.0.1:1337:1337
    networks:
      - yearn-brownie-bridge
    restart: on-failure

  brownie-bridge-ftm:
    build: .
    image: yearn-exporter
    command: brownie_bridge
    volumes: *common-volumes
    environment:
      <<: *common-envs
      <<: *common-ftm-envs
    ports:
        - 127.0.0.1:1338:1337
    networks:
      - yearn-brownie-bridge
    restart: on-failure
